.TH "AttackArea" 3 "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AttackArea
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnTriggerEnter\fP (Collider other)"
.br
.RI "WHen something is in field of view, we check if it is enemy and of so we attack it\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBdamage\fP = 3"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void AttackArea\&.OnTriggerEnter (Collider other)\fR [private]\fP"

.PP
WHen something is in field of view, we check if it is enemy and of so we attack it\&. 
.SH "Member Data Documentation"
.PP 
.SS "int AttackArea\&.damage = 3\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
