.TH "CharacterAnimatorManager" 3 "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterAnimatorManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBPlayerAnimatorManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateAnimatorParameter\fP (string parameterName, bool value)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBCharacterManager\fP \fBcharacter\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void CharacterAnimatorManager\&.Awake ()\fR [protected]\fP, \fR [virtual]\fP"

.SS "void CharacterAnimatorManager\&.UpdateAnimatorParameter (string parameterName, bool value)"

.SH "Member Data Documentation"
.PP 
.SS "\fBCharacterManager\fP CharacterAnimatorManager\&.character\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
