.TH "CharacterLocomotionManager" 3 "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharacterLocomotionManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.PP
Inherited by \fBPlayerLocomotionManager\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual void CharacterLocomotionManager\&.Awake ()\fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBPlayerLocomotionManager\fP\&.
.SS "virtual void CharacterLocomotionManager\&.Update ()\fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBPlayerLocomotionManager\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
