.TH "D:/D/gnom/Gnomes-2.0/Assets/Scripts Directory Reference" 3 "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/D/gnom/Gnomes-2.0/Assets/Scripts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCharacter\fP"
.br
.ti -1c
.RI "directory \fBEntity\fP"
.br
.ti -1c
.RI "directory \fBGameplayManagers\fP"
.br
.ti -1c
.RI "directory \fBMenu Scene\fP"
.br
.ti -1c
.RI "directory \fBPlayerFight\fP"
.br
.ti -1c
.RI "directory \fBWorld Managers\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPlayerInputActions\&.cs\fP"
.br
.ti -1c
.RI "file \fBPlayerInputManager\&.cs\fP"
.br
.in -1c
