.TH "IDamagable" 3 "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IDamagable
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtakeDamage\fP (int damage)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void IDamagable\&.takeDamage (int damage)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
