.TH "PlayerAnimatorManager" 3 "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerAnimatorManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCharacterAnimatorManager\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBCharacterAnimatorManager\fP
.in +1c
.ti -1c
.RI "void \fBUpdateAnimatorParameter\fP (string parameterName, bool value)"
.br
.in -1c

Protected Member Functions inherited from \fBCharacterAnimatorManager\fP
.in +1c
.ti -1c
.RI "virtual void \fBAwake\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
