.TH "PlayerInputActions.IPlayerActions" 3 "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayerInputActions.IPlayerActions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnMove\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnJump\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnAttack\fP (InputAction\&.CallbackContext context)"
.br
.ti -1c
.RI "void \fBOnRun\fP (InputAction\&.CallbackContext context)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void PlayerInputActions\&.IPlayerActions\&.OnAttack (InputAction\&.CallbackContext context)"

.SS "void PlayerInputActions\&.IPlayerActions\&.OnJump (InputAction\&.CallbackContext context)"

.SS "void PlayerInputActions\&.IPlayerActions\&.OnMove (InputAction\&.CallbackContext context)"

.SS "void PlayerInputActions\&.IPlayerActions\&.OnRun (InputAction\&.CallbackContext context)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
